services:
  - type: web
    name: voicenotes-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SPEECH_KEY
        sync: false
      - key: SPEECH_REGION
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ENDPOINT
        sync: false
      - key: OPENAI_DEPLOYMENT
        sync: false
